name: Build fonts

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout Iosevka repository
        uses: actions/checkout@v4
        with:
          repository: be5invis/Iosevka
          path: iosevka

      - name: Copy custom configuration
        run: |
          cp private-build-plans.toml iosevka/private-build-plans.toml

      - name: Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y ttfautohint
          cd iosevka
          bun install

      - name: Build Iosevka fonts
        run: |
          cd iosevka
          bun run build -- ttf::IosevkaCustom

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: iosevka-fonts
          path: iosevka/dist/IosevkaCustom/TTF/*.ttf
          if-no-files-found: error
          retention-days: 7